[server]
port = 3000
name = "Lagos-Main-Gateway"
ssl_enabled = false

[services.products]
target = "http://localhost:3001"
strip_prefix = true
auth_required = false

[services.users]
target = "http://localhost:8000"
strip_prefix = true
auth_required = true